# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: questionnaireservice
services:
  app:
    image: questionnaireservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_COUCHBASE_CONNECTION_STRING=couchbase
      - JHIPSTER_DATABASE_COUCHBASE_BUCKET_NAME=QuestionnaireService
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/thg-questionnaire-service
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=questionnaire-service
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET}
      - JHIPSTER_SLEEP=20
    ports:
      - 127.0.0.1:8071:8071
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8071/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      couchbase:
        condition: service_healthy
  couchbase:
    extends:
      file: ./couchbase.yml
      service: couchbase
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
